# Generated by Django 4.1 on 2022-09-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoListItem',
        ),
    ]
