# Generated by Django 4.1 on 2022-09-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlistitem',
            old_name='movie_rating',
            new_name='movie_rate',
        ),
        migrations.RenameField(
            model_name='mywatchlistitem',
            old_name='movie_name',
            new_name='movie_title',
        ),
    ]
